### ISSUE TITLE
Hash

### ISSUE THREAD

**Issue by qwerty3345** [TeddysRoom/Algo-rhythm#13]
9/30
[link](https://www.youtube.com/watch?v=1-k-D2AYY0I&list=PLtqbFd2VIQv4O6D6l9HcD732hdrnYb6CY&index=22)

**Comment by shippingpark** [comment]
> 코테가 급하다면 정의와 성질, STL 사용법만 보고 넘어가기 
> 제대로 보고자 한다면 충돌회피와 구현을 제대로 볼 것 
### 정의 
임의 길이 데이터를 고정 길이 데이터로 대응시키는 함수 
키에 대응되는 값을 저장하는 자료 구조 
키를 배열의 인덱스로 보내는 함수를 하나 둬서 테이블로 관리하는 게 해시 자료구조

**Comment by MUKER-WON** [comment]
## 해시 (Hash) 함수

- 임의의 길이를 가진 데이터를 고정된 길이의 데이터로 변환하는 함수
- 해시를 직접 구현할 일은 드물지만 개념을 이해하고 쓰면 더 맛도리

### 주요 특징

- 고정된 출력 길이: 입력 값의 길이와 상관없이 항상 고정된 길이의 출력을 생성
- 결정론적 특성: 동일한 입력에 대해서는 항상 같은 해시 값을 반환
- 충돌 회피: 서로 다른 입력에 대해 같은 해시 값을 반환하는 경우가 적어야 함
- 빠른 계산: 입력 값에 대해 해시 값을 빠르게 계산할 수 있어야 함

## 충돌 회피

- 충돌은 서로 다른 입력 값들이 같은 새히 값을 가질 때 발생하며, 이를 효과적으로 처리하지 않으면 해시 테이블의 성능이 저할될 수 있다.

### Chaining

- 동일한 해시 값을 가진 데이터를 `연결 리스트` 로 저장하는 방식
- 해시 테이블의 각 슬롯이 하나의 연결 리스트를 가리키며, 충돌이 발생하면 해당 슬롯의 리스트에 새 데이터를 추가하는 방식

### Open Addressing

- 테이블 내의 빈 공간을 찾아 데이터를 저장하는 방식. 여러 전략들이 있음
- 메모리 사용을 더 잘 관리할 수 있으나, 충돌이 많아질 경우 성능 저하가 발생
- Open Addressing 방식들
    - `Linear Probing`: 충돌이 발생하면 다음 슬롯을 순차적으로 확인하여 빈 슬롯을 찾는 방식. 해시 값이 충돌할 경우 인덱스를 1씩 증가시켜 빈 슬롯을 찾음
    - `Quadratic Probing`: 충돌이 발생하면 범위를 제곱수로 증가시켜 슬롯을 찾는 방식. 충돌 시 처음에는 1칸, 다음에는 4칸, 다음은 9칸 이동하며 찾음
    - `Double Hashing`: 충돌 시, 두 번째 해시 함수를 사용해 새로운 슬롯을 찾는 방식. 첫 번째 해시 함수로 충돌이 발생하면, 두 번째 해시 함수의 결과로 다음 탐색할 슬롯을 결정.

**Comment by shippingpark** [comment]
### 나는야 포켓몬 마스터 이다솜 문제

```swift 
import Foundation

let input = readLine()!.split(separator: " ").map { Int($0)! },
N = input[0], M = input[1]
var arr: [String] = Array(repeating: "", count: N+1)
var dic: [String: Int] = [:]

for num in 1...N {
  let poketmon: String = readLine()!
  arr[num] = poketmon
  dic[poketmon] = num
}

for _ in 1...M {
  let question: String = readLine()!
  if let num = Int(question) {
    print(arr[num])
  } else {
    print(dic[question] ?? "")
  }
}
```

**Comment by qwerty3345** [comment]
## [나는야 포켓몬 마스터 이다솜](https://www.acmicpc.net/problem/1620)
- 지문을 읽지 말자 (?)
```swift
let input = readLine()!.components(separatedBy: " ").compactMap { Int($0) }
let (N, M) = (input[0], input[1])

var pocketmons: [String] = [""]
pocketmons.reserveCapacity(N + 1)
var indexByPocketmon: [String: Int] = [:]

for index in 1...N {
    let pocketmon = readLine()!
    pocketmons.append(pocketmon)
    indexByPocketmon[pocketmon] = index
}

for _ in 0..<M {
    let input = readLine()!
    if let index = Int(input) {
        print(pocketmons[index])
    } else {
        print(indexByPocketmon[input]!)
    }
}
```

**Comment by MUKER-WON** [comment]
## 포켓몬 마스터 이다솜

- 입출력은 까지 대화형으로 서술 하지마...
```swift
let I = readLine()!.split { $0 == " " }.map { Int($0)! }
var monsterNumbers = [String: Int]()
let monsters = (1...I[0]).map { i -> String in
    let str = readLine()!
    monsterNumbers[str, default: 0] = i
    return str
}

(0..<I[1]).forEach { _ in
    let n = readLine()!
    if let num = Int(n) {
        print(monsters[num-1])
    } else {
        print(monsterNumbers[n]!)
    }
}
```
