### ISSUE TITLE
Tree

### ISSUE THREAD

**Issue by MUKER-WON** [TeddysRoom/Algo-rhythm#17]
10/8
[Link](https://www.youtube.com/watch?v=nehRy6hAJsA&list=PLtqbFd2VIQv4O6D6l9HcD732hdrnYb6CY&index=26)

**Comment by stealmh** [comment]
# 트리
무방향이면서 사이클이 없는 연결그래프를 뜻한다
만약 사이클이 있는 모습을 취한다면 점선 형태의 간선이 추가되는 것으로 나타낼 수 있지만 이는 트리라고 볼 수 없는 모양을 하게 되며 결국은 트리가 아니게 된다.

정점이 1개에 간선이 없는 그래프도 트리라고 볼 수 있음
V개의 정점을 가지고 V-1개의 간선을 가지는 연결 그래프 ‼️

임의의 두 점을 연결하는 simple path가 유일하다 ‼️

트리에서는 임의의 노드를 루트로 만들 수 있다. 아무 노드나 선택해 최상단으로 올리면 된다.
루트가 달라지면 각 노드의 부모는 당연하게도 달라진다.

## 트리의 BFS
루트가 아닌 정점을 선택했을 때 인접한 정점들 중에 자신의 부모를 제외하고 전부 자신의 자식이라 아직 방문하지 않았음
트리에서는 BFS 과정중 자신의 자식을 전부 큐에 넣어주는 과정을 거친다.
부모가 누구인지만 저장하고 있으면 됨, dfs는 큐 대신 stack을 사용해 구현하는 것으로 대체 가능 

## 이진트리에서의 순회
이진트리에서 사용하는 순회에는 다음과 같은 목록이 존재
1. 레벨순회
2. 전위 순회
3. 중위 순회
4. 후위 순회

순회를 확인하기 이전 이진트리를 코드에서 표현하는 방법은 다음과 같음
-> 왼쪽 자식과 오른쪽 자식을 저장하게 코드를 구성하자
배열에서 0이라는 값은 해당 자리가 비어있음을 의미한다. lc[4] = 0 이라면 4의 왼쪽 자식이 없다는 것을 의미하게 된다.

### 레벨순회
높이 순으로 방문하는 순회를 말한다. 루트가 1, 1의 자식이 2,3 이라면 1,2,3 순으로 확인하는 것이 바로 레벨 순회라고 할 수 있다. 사실 우리는 레벨 순회를 이미 사용하고 있다. 루트에서 BFS를 돌리게 되면 자연스레 레벨 순회가 됨을 알고 있기 때문에 루트를 시작점으로 두고 BFS를 돌려 구현을 하자

이진 트리를 배열로 (lc, rc)로 표현하고 있기 때문에 시작점이 루트라고 가정한 트리 모양에서 현재 보는 정점의 자식들을 큐에 넣어주는 방식으로 구현한다

### 전위 순회
1. 현재 정점 방문
2. 왼쪽 전위 순회
3. 오른쪽 전위 순회

자식의 노드를 왼쪽으로 끝까지 파고든다. 왼쪽이 없다면 한칸 위로 올라와서 3번을 수행한다. 3번이 없다면 다시 위로 한칸 올라온다. 즉 리프에 경우에는 2,3번을 수헹하지 않기 때문에 자기 자신만 방문처리하게 된다.

전위 순회는 DFS와 방문 순서가 동일함
구현은 재귀를 통해 아주 간단하게 구현 가능한데 자기 자신을 출력하고 왼쪽자식과 오른쪽 자식 각각에 대해 존재할 경우 전위 순회를 하도록 구현하는 것으로 해결할 수 있음

### 중위 순회
왼쪽 서브트리 -> 자기 자신 -> 오른쪽 서브트리 순으로 처리하는 순회 방법
트리가 만약 이진 탐색 트리라면 자연스럽게 크기 순으로 방문하게 된다

### 후위 순회
왼쪽 서브트리 -> 오른쪽 서브트리 -> 자기 자신 순으로 처리하는 순회 방법

**Comment by MUKER-WON** [comment]
# 트리 (Tree)

- 무방향이면서 사이클이 없는 연결 그래프
- V개의 정점을 가지고 V-1개의 간선을 가지는 연결 그래프

## 이진 트리의 순회

- 이진 트리를 구조체로 만들어 표현해도 되지만 lc,rc 배열을 각각만들어 저장할 수 있다.

### 레벨 순회

- 높이 순으로 방문하는 순회하는 방법 (BFS)

### 전위 순회 (Preorder Traversal)

- 재귀 DFS와 방문 순서가 동일하다.
1. 현재 정점을 방문한다.
2. 왼쪽 서브 트리르 전위 순회한다.
3. 오른쪽 서브 트리를 전위 순회한다.

### 중위 순회 (Inorder Traversal)

1. 왼쪽 서브 트리를 중위 순회한다.
2. 현재 정점을 방문한다.
3. 오른쪽 서브 트리를 중위 순회 한다.

### 후위 순회 (Postorder Traversal)

1. 왼쪽 서브 트리를 후위 순회한다.
2. 오른쪽 서브 트리를 후위 순회한다.
3. 현재 정점을 방문한다.

## 문제 풀이

### BOJ 11725번: 트리의 부모 찾기

- dfs로 문제 풀이
```swift
let N = Int(readLine()!)!
var arr = Array(repeating: [Int](), count: N+1)
var ans = Array(repeating: 0, count: N+1)

for _ in 1..<N {
    let I = readLine()!.split { $0 == " " }.map { Int($0)! }
    arr[I[0]].append(I[1])
    arr[I[1]].append(I[0])
}

func dfs(_ parent: Int) {
    for child in arr[parent] {
        if ans[child] != 0 { continue }
        ans[child] = parent
        dfs(child)
    }
}

dfs(1)
ans[2...].forEach { print($0) }
```

**Comment by qwerty3345** [comment]
# 트리 (Tree)

## 1. 트리의 개념
- 무방향이면서 사이클이 없는 연결 그래프
- 계층 구조를 가짐 (루트, 부모, 자식, 리프 등의 개념)

## 2. 트리의 성질
- V개의 정점을 가진 트리는 V-1개의 간선을 가짐
- 임의의 두 점을 연결하는 경로가 유일함

## 3. 트리의 표현
- 인접 리스트 또는 부모 배열 사용
- 이진 트리의 경우 left child, right child 배열 사용 가능

## 4. 트리의 순회
### 4.1 BFS (너비 우선 탐색)
- 레벨 순서대로 방문
- 큐를 사용하여 구현

### 4.2 DFS (깊이 우선 탐색)
- 재귀 또는 스택을 사용하여 구현
- 부모 정보만으로 구현 가능

### 4.3 이진 트리의 순회
- 전위 순회 (Preorder): 루트 -> 왼쪽 -> 오른쪽
- 중위 순회 (Inorder): 왼쪽 -> 루트 -> 오른쪽
- 후위 순회 (Postorder): 왼쪽 -> 오른쪽 -> 루트
- 레벨 순회 (Level-order): BFS와 동일

## 5. 구현 시 주의사항
- 재귀를 사용할 경우 스택 오버플로우 주의
- 이진 트리 표현 시 left child, right child 배열 활용

## 6. 응용
- 트리의 부모 찾기
- 트리 순회 결과 출력

## 7. 심화 주제
- 트리 DP (Dynamic Programming on Trees)

## BOJ 11725번: 트리의 부모 찾기
```swift
import Foundation

let N = Int(readLine()!)!
var tree: [Int: [Int]] = [:]
for _ in 1..<N {
    let input = readLine()!.components(separatedBy: " ").compactMap { Int($0) }
    tree[input[0], default: []].append(input[1])
    tree[input[1], default: []].append(input[0])
}

var parentByNode: [Int: Int] = [:]

var queue: [Int] = []
var visited: [Int: Bool] = tree.keys.reduce(into: [:]) { $0[$1] = false }

queue.append(1)

while queue.isEmpty == false {
    let node = queue.removeFirst()
    if visited[node] == true { continue }
    visited[node] = true

    let connectedNodes = tree[node] ?? []
    for connectedNode in connectedNodes {
        if visited[connectedNode] == false {
            queue.append(connectedNode)
            parentByNode[connectedNode] = node
        }
    }
}

for node in 2...N {
    print(parentByNode[node] ?? 0)
}
```

**Comment by shippingpark** [comment]
# 트리 
> 무방향이면서 사이클이 없는 연결 그래프 
> 정점이 1개이고 간선이 없는 그래프도 트리다 
### 성질 
1) V개의 정점을 가지고 V-1개의 간선을 가지는 연결 그래프 
2) 임의의 두 점을 연결하는 simple path(정점이 중복해서 나오지 않는 경로)가 유일한 그래프 

# `트리`에서의 BFS 
트리의 BFS의 독특한 점. 
인접한 정점들 중에 자신을 제외하고 자식들을 전부 큐에 넣어주면 된다 (이웃한 정점들 중에 부모와 자신을 빼고 넣으면 된다) 그렇기 때문에 vis 배열을 들고 갈 필요없이 부모가 누구인지 저장하고 있으면 됌 

# `트리` 에서의 DFS 
쭉쭉 가다가 더 이상 갈 수 없으면 다른 거. 
자신과 연결된 정점들은 1개만 부모이고, 전부 자식이라는 성질을 이용하여 부모 배열과 depth 배열만 활용하여 처리 가능 

## `재귀`에서의 DFS 
스택 메모리가 1메가 등 고정되어 있을 때에는 주의 해야 한다 
부모 배열과 뎁스에 저장할 필요 없이 단순 순회가 목적이라면 코드가 굉장히 간단해짐  

# 이진 트리의 순회 
## 이진트리를 코드에서 표현하는 방법 
왼쪽 자식과 오른쪽 자식을 전부 저장하게끔 구현하면 좋음 
<img width="396" alt="image" src="https://github.com/user-attachments/assets/b61cd840-7b8f-4c67-b906-3a96f4e707ce">


## 레벨 순회 
높이 순으로 방문하는 순회 
루트에서 BFS를 돌리면 자연스럽게 레벨 순회가 된다 
lc rc로 배열을 가지고 있는 상황이기 때문에, 이에 맞게 BFS를 사용하려면 현재 정점의 자식을 넣어주면 된다 

## 전위/중위/후위 순회 
> 전위 순회를 이해하고 나면 나머지도 크게 어렵지 않음 

### 전위 순회 (재귀적으로 접근 가능)
1. 현재 정점을 방문 
2. 왼쪽 서브 트리를 전위 순회
3. 오른쪽 서브 트리를 전위 순회 

> DFS 방문 순서와 동일하다 

재귀를 이용하여 아주 간단하게 구현 가능 
왼쪽과 오른쪽 자식 각각에 대해 존재할 경우 전위 순회를 하도록 구현하면 됨 

### 중위 순회 
왼쪽 서브트리 -> 나 -> 오른쪽 서브트리 순으로 
1. 왼쪽 서브 트리를 중위 순회한다 
2. 현재 정점을 방문한다 
3. 오른쪽 서브 트리를 중위 순회한다 

### 후위 순회 
왼쪽 서브트리 -> 오른쪽 서브트리 -> 나 
1. 왼쪽 서브트리를 후위 순회한다 
2. 오른쪽 서브트리를 후위 순회한다 
3. 현재 정점을 방문한다 

### 정리 
서로 다른 트리더라도 중위 순회 결과가 일치할 수 있음 

<img width="746" alt="image" src="https://github.com/user-attachments/assets/124ae621-f908-484f-9f65-c375e99f3088">
