### ISSUE TITLE
Topology Sort

### ISSUE THREAD

**Issue by MUKER-WON** [TeddysRoom/Algo-rhythm#18]
10/10
[Link](https://www.youtube.com/watch?v=Th-gLZUrd04&list=PLtqbFd2VIQv4O6D6l9HcD732hdrnYb6CY&index=27)

**Comment by MUKER-WON** [comment]
## 위상 정렬 (Topology Sort)

- 방향 그래프에서 간선으로 주어진 정점 간 선후관계를 위배하지 않도록 나열하는 정렬
- 그래프 안에 사이클이 존재할 경우에는 올바른 위상 정렬이 존재할 수 없다.
- 사이클이 존재하지 않는 방향 그래프를 DAG(Directed Acyclic Graph)라고 줄여 부르기도 한다.

### 위상 정렬 구현 성질

1. 정점과 간선을 실제로 지울 필요 없이 미리 indegree의 값을 저장했다가 매번 뻗어나가는 정점들의 indegree 값만 1감소 시켜 과정을 수행
2. indegree가 0인 정점을 구하기 위해 매번 모든 정점들을 다 확인하는 대신 목록을 따로 저장하고 있다가 직전에 제거한 정점에서 연결된 정점들만 추가

### 위상 정렬 구현 순서

1. 맨 처음 모든 간선을 읽으며 indegree 테이블을 채움
2. indegree가 0인 정점들을 모두 큐(스택)에 넣음
3. 큐(스택)에서 정점을 꺼내어 위상 정렬 결과에 추가
4. 해당 정점으로부터 연결된 모든 정점의 indegre 값을 1 감소시킴 이 때 indegree가 0이 되었다면 그 정점을 큐(스택)에 추가
5. 큐(스택)가 빌 때 까지 3,4번 과정을 반복

## 문제 풀이

### BOJ 2252번: 줄 세우기

**Comment by stealmh** [comment]
# 위상정렬

위상정렬은 다음과 같다.
수강신청을 해야할 때 수학1 수학2와 같은 과목이 있다면 수학2는 반드시 수학1을 수강하고 난 후 신청할 수 있는 것으로 쉽게 비유할 수 있다.

>방향 그래프에서 간선으로 주어진 정점 간 선후관계를 위배하지 않도록 나열하는 정렬

위상정렬은 그래프 내 사이클이 존재할 수 없다.
각각 사이클이 있는 ABC정점이 있을 때 어떤 것이 먼저 나오더라도 모순이 발생하기 때문
따라서 위상정렬은 사이클이 존재하지 않는 방향 그래프에서만 정의되며, 사이클이 존재하지 않는 방향 그래프는 `DAG(Directed Acyclic Graph)` 

## 알고리즘 구현
1. 모든 간선을 읽으며 indegree 테이블 채우기
2. indegree가 0인 정점들을 모두 큐에 넣기
3. 큐에서 정점을 꺼내어 위상 정렬 결과에 추가
4. 해당 정점으로부터 연결된 모든 정점의 indegree 값을 1감소시킨다. indegree가 0이 되었다면 그 정점을 큐에 추가한다.
5. 큐가 비어있을 때 까지 3,4번 과정을 반복

## 연습문제
BOJ 2252: 줄세우기

<details>
<summary>코드</summary>

```swift
let input = readLine()!.split(separator: " ").map { Int($0)! }
let (N, M) = (input[0], input[1])

var array = [[Int]](repeating: [], count: N + 1)
var degree = [Int](repeating: 0, count: N + 1)
var queue = [Int]()
var result = [Int]()

for _ in 0..<M {
    let input = readLine()!.split(separator: " ").map { Int($0)! }
    let (start, end) = (input[0], input[1])
    
    array[start].append(end)
    degree[end] += 1
}

for i in 1...N {
    if degree[i] == 0 { queue.append(i) }
}

while !queue.isEmpty {
    let first = queue.removeFirst()
    
    for i in array[first] {
        degree[i] -= 1
        
        if degree[i] == 0 { queue.append(i) }
    }
    
    result.append(first)
}

print(result.map { String($0) }.joined(separator: " "))

```
</details>

**Comment by qwerty3345** [comment]
# 위상 정렬 (Topological Sort)

## 1. 개념
- 방향 그래프에서 간선으로 주어진 정점 간 선후관계를 위배하지 않도록 나열하는 정렬
- 사이클이 없는 방향 그래프(DAG)에서만 가능

## 2. 알고리즘
1. 모든 정점의 진입차수(indegree) 계산
2. 진입차수가 0인 정점을 큐에 삽입
3. 큐에서 정점을 꺼내어 위상 정렬 결과에 추가
4. 해당 정점에서 나가는 간선 제거 (연결된 정점의 진입차수 감소)
5. 진입차수가 0이 된 정점을 큐에 삽입
6. 2-5 과정 반복

## 3. Swift 구현

```swift
func topologicalSort(_ n: Int, _ edges: [(Int, Int)]) -> [Int]? {
    var graph = [Int: [Int]]()
    var inDegree = [Int](repeating: 0, count: n + 1)
    
    // 그래프 구성 및 진입차수 계산
    for (a, b) in edges {
        graph[a, default: []].append(b)
        inDegree[b] += 1
    }
    
    var queue = [Int]()
    for i in 1...n where inDegree[i] == 0 {
        queue.append(i)
    }
    
    var result = [Int]()
    
    while !queue.isEmpty {
        let node = queue.removeFirst()
        result.append(node)
        
        for next in graph[node, default: []] {
            inDegree[next] -= 1
            if inDegree[next] == 0 {
                queue.append(next)
            }
        }
    }
    
    return result.count == n ? result : nil
}
```

## 4. 사용 예시

```swift
let n = 6
let edges = [(1, 2), (1, 3), (2, 4), (3, 4), (3, 5), (4, 6), (5, 6)]

if let result = topologicalSort(n, edges) {
    print("위상 정렬 결과: \(result)")
} else {
    print("사이클이 존재하여 위상 정렬 불가능")
}
```

## 5. 특징
- 여러 가지 위상 정렬 결과가 가능할 수 있음
- 사이클이 있으면 위상 정렬 불가능 (알고리즘 종료 후 정점 수 확인)
- 시간복잡도: O(V+E)

## 6. 응용
- 작업 순서 결정
- 선수과목 관계 처리
- 위상 정렬 DP (고급)

## 7. 주의사항
- 그래프에 사이클이 없어야 함
- 정점 간 선후관계가 주어진 문제에 적용 가능
- 결과의 길이가 노드의 수와 같지 않으면 사이클이 존재한다는 의미


### [BOJ 2252번: 줄 세우기](https://www.acmicpc.net/problem/2252)
```swift
import Foundation

let input = readLine()!.components(separatedBy: " ").compactMap { Int($0) }
let (N, M) = (input[0], input[1])

var indegreeCount = Array(repeating: 0, count: N + 1)
var graph = Array(repeating: [Int](), count: N + 1)

for _ in 0..<M {
    let input = readLine()!.components(separatedBy: " ").compactMap { Int($0) }
    let (nodeA, nodeB) = (input[0], input[1])
    indegreeCount[nodeB] += 1    // b의 indegree 수 증가
    graph[nodeA].append(nodeB)   // a -> b 간선
}

let zeroIndegreeNodes = (1...N)
    .filter {
        indegreeCount[$0] == 0
    }

var queue = zeroIndegreeNodes
var result: [Int] = []

while queue.isEmpty == false {
    let current = queue.removeFirst()
    result.append(current)

    for node in graph[current] {
        indegreeCount[node] -= 1
        if indegreeCount[node] == 0 {
            queue.append(node)
        }
    }
}

print(result.map { String($0) }.joined(separator: " "))
```

**Comment by shippingpark** [comment]
# 위상정렬 
> 대표적인 예시, 선후수과목 
정점 간의 선후관계를 위배하지 않도록 나타내는 정렬 

제일 앞에 오기 위해서는 , 자신에게 들어오는 간선이 없어야 함 
즉, 구현 또한 들어오는 간선이 없는 정점을 먼저 제거해주면 됨 

# 구현 편의를 위한 성질 
막무가내로 하면 O(V^2)에 가까운 형태로 진행하게 됨 
직전에 제거한 정점들이 가진 다음 정점을 추가하면 된다 

# 위상 정렬 알고리즘 
1. 맨 처음 모든 간선을 읽으며 indegree 테이블을 채움 
2. Indegree가 0인 정점들을 모두 큐에 넣음 
3. 큐에서 정점을 꺼내어 위상 정렬 결과에 추가
4. 해당 정점으로부터 연결된 모든 정점의 indegree 값을 1 감소시킴 이 때 indegree가 0이 되었다면 그 정점을 큐에 추가 
5. 큐가 빌 때 까지, 3, 4번 과정을 반복 

### 주의 
위상정렬결과에 모든 정점이 없다면 싸이클이 존재했음을 추측 가능 

```swift 
import Foundation

let input = readLine()!.split(separator: " ").compactMap { Int($0) },
(N, M) = (input[0], input[1])

var graph = Array(repeating: [Int](), count: N+1)
var indgree = Array(repeating: 0, count: N+1)

for _ in 0..<M {
  let input = readLine()!.split(separator: " ").compactMap { Int($0) },
  (A, B) = (input[0], input[1])
  
  graph[A].append(B)
  indgree[B] += 1
}

var queue = (1...N).filter { indgree[$0] == 0 }
var result = [Int]()

while !queue.isEmpty {
  let now = queue.removeFirst()
  result.append(now)
  
  for child in graph[now] {
    indgree[child] -= 1
    
    if indgree[child] == 0 {
      queue.append(child)
    }
  }
}

print(result.map { String($0) }.joined(separator: " "))
```
