### ISSUE TITLE
Minimum Spanning Tree

### ISSUE THREAD

**Issue by MUKER-WON** [TeddysRoom/Algo-rhythm#19]
10/11
[Link](https://www.youtube.com/watch?v=4wA3bncb64E&list=PLtqbFd2VIQv4O6D6l9HcD732hdrnYb6CY&index=28)

**Comment by MUKER-WON** [comment]
# 최소 신장 트리 (MST, Minimum Spanning Tree)

- 신장 트리 중에서 간선의 합이 최소인 트리

## 신장 트리

- 주어진 방향성이 없는 그래프의 부분 그래프들 중에서 모든 정점을 포함하는 트리
- 부분 그래프는 주어진 그래프에서 일부 정점과 간선만을 택해서 구성한 새로운 그래프
- 트리의 성질로부터 주어진 그래프의 정점이 V개일 때 신장 트리는 V-1개의 간선을 가지고 있다.
- 주어진 그래프가 연결 그래프일 때만 신장 트리가 존재

## 크루스칼 알고리즘

- 비용이 가장 낮은 간선부터 시작해 간선을 크기순으로 살펴보며 서로 떨어져 있던 정점들을 합쳐나가서 총 V-1개의 간선을 택하는 알고리즘
- Union Find라는 알고리즘을 모르는 효율적으로 구현할 수 없다.
- 그저 알고리즘의 절차만 보면 `비용이 작은 간선부터 최소 신장 트리에 편입시키는 그리디 알고리즘`이다.
- Union Find를 이용해서 크루스칼 알고리즘을 구현하면 O(ElgE + VE) 대신 O(ElgE)로 해결할 수 있다.

### 크루스칼 알고리즘의 과정

1. 간선을 크기의 오름차순으로 정렬하고 제일 낮은 비용의 간선을 선택
2. 현재 선택한 간선이 정점 u,v를 연결하는 간선이라고 할 때 만약 u와 v가 같은 그룹이라면 아무 것도 하지 않고 넘어감, u와 v가 다른 그룹이라면 같은 그룹으로 만들고 현재 선택한 간선을 최소 신장 트리에 추가
3. 최소 신장 트리에 V-1개의 간선을 추가시켰다면 과정을 종료, 그렇지 않다면 그 다음으로 비용이 작은 간선을 선택 후 2번 과정을 반복

## 프림 알고리즘

- 하나의 정점을 선택해 우선순위에 적합한 간선을 선택해 최소 신장 트리에 추가하는 방식
- 크루스칼 알고리즘과 다르게 우선순위 큐로 구현 가능(Swift에선.. 웃을 수 없는 얘기ㅠ), 시간복잡도만 따라준다면 그냥 sorted()를 이용해 우선순위 큐처럼 작동하게 구현하는 것도 방법일 듯
- 마찬가지로 그리디 알고리즘의 형태이다.

### 프림 알고리즘의 과정

1. 임의의 정점을 선택해 최소 신장 트리에 추가, 해당 정점과 연결된 모든 간선을 우선순위 큐에 추가
2. 우선순위 큐에서 비용이 가장 작은 간선을 선택
3. 만약 해당 간선이 최소 신장 트리에 포함된 두 정점을 연경한다면 아무 것도 하지 않고 넘어감, 해당 간선이 최소 신장 트리에 포함된 정점 u와 포함되지 않은 정점 v를 연결한다면 해당 간선과 정점 v를 최소 신장 트리에 추가 후 정점 v와 최소 신장 트리에 포함되지 않는 정점을 연결하는 모든 간선을 우선순위 큐에 추가
4. 최소 신장 트리에 V-1개의 간선이 추가될 때 까지 2,3번 과정을 반복

**Comment by stealmh** [comment]
# 최소 신장 트리

신장트리는 무엇일까?
주어진 방향성이 없는 그래프의 부분 그래프들 중에서 모든 정점을 포함하는 트리
부분 그래프는 일부의 정점, 간선을 이용해 구성한 새로운 그래프를 의미함
당연하게도 연결 그래프일때만 신장트리가 존재한다.

## 크루스칼 알고리즘
가장 비용이 낮은 간선부터 시작해 간선을 크기 순으로 살펴보며 서로 떨어져 있던 정점들을 합쳐나가서 총 V-1개의 간선을 택하는 알고리즘

크루스칼 알고리즘은 기본적으로 그룹을 나눔으로써 최소간선을 택하는 형식이다.
초기에 각 정점을 다른 그룹으로 지정을 한 뒤 가장 최소값의 간선을 선택한다.
간선으로 연결된 정점은 같은 그룹이 된다. 이후 각 정점에서 연결된 나머지 간선들 중 최소 비용을 찾는다. 모든 정점이 같은 그룹으로 묶였다면 지금까지 지나왔던 간선들을 더한다. 이는 최소 신장 트리이다. 

이 방법은 그리디 알고리즘을 사용한다.

## 프림 알고리즘

**Comment by shippingpark** [comment]
# 최소 신장 트리 (MST, Minimum Spanning Tree)

MST는 **모든 정점을 연결하면서 간선 비용을 최소로** 하는 트리임. 주어진 그래프에서 **연결 그래프**일 때만 신장 트리를 만들 수 있음.

---

## 크루스칼 알고리즘 (Kruskal's Algorithm)

크루스칼 알고리즘은 **가장 적은 비용의 간선부터** 추가하는 방식임. 이를 통해 정점을 **같은 그룹**으로 묶으며 최소 신장 트리를 구성함. **Union-Find**를 사용하면 더 효율적임.

### 요약
1. 간선을 **오름차순으로 정렬**함.
2. 서로 **다른 그룹**을 연결하는 간선을 선택함.
3. 그룹이 같으면 무시하고, 다르면 **추가**함.
4. **V-1개의 간선**이 선택될 때까지 반복함.

---

## 프림 알고리즘 (Prim's Algorithm)

프림 알고리즘은 **한 정점에서 시작**해, 연결된 간선 중 **가장 적은 비용**의 간선을 선택해 나가는 방식임. 우선순위 큐를 사용하면 더 쉽게 구현할 수 있음.

### 요약
1. **임의의 정점**을 선택함.
2. 해당 정점에 연결된 **모든 간선**을 우선순위 큐에 넣음.
3. 비용이 **가장 작은 간선**을 선택해 트리에 추가함.
4. **V-1개의 간선**이 선택될 때까지 반복함.

---

## 차이점 요약
- **크루스칼**은 간선을 정렬해 처리함.
- **프림**은 한 정점에서 출발해 최소 비용 간선을 찾아 확장함.

둘 다 **그리디 알고리즘**으로 작동하며, 비용을 최소화하는 것을 목표로 함.
