### ISSUE TITLE
KMP

### ISSUE THREAD

**Issue by MUKER-WON** [TeddysRoom/Algo-rhythm#22]
10/16
[Link](https://www.youtube.com/watch?v=9bkbV-VANQ0&list=PLtqbFd2VIQv4O6D6l9HcD732hdrnYb6CY&index=31)

**Comment by MUKER-WON** [comment]
# 문자열 매칭 알고리즘 (KMP)

- 문자열에서 패턴을 효츌적으로 찾는 알고리즘, 중복된 비교를 피하는 방식으로 설계 됨
- 시간복잡도는 `O(n+m)` , n은 텍스트 길이, m은 패턴 길이

## 실패 함수

- 문자열 S[0…x]에서 `접두사와 접미사가 일치하는 최대 길이`
- 즉 밑의 문자열을 움직일 필요가 없이 위와 아래 각각에서 이전에 확인한 문자열들의 다음 칸에 해당하는 두 글자가 일치하는지 확인하면 된다.
- DP를 이용해 F(x-1)번째의 값을 이용해 F(x)의 값을 계산할 수 있다.

```swift
// 패턴 "ABABCABAB"

1.	"A": 접두사와 접미사가 일치하지 않음 → 0
2.	"AB": 접두사와 접미사가 일치하지 않음 → 0
3.	"ABA": 접두사 "A"와 접미사 "A"가 일치함 → 1
4.	"ABAB": 접두사 "AB"와 접미사 "AB"가 일치함 → 2
5.	"ABABC": 접두사와 접미사가 일치하지 않음 → 0
6.	"ABABCA": 접두사 "A"와 접미사 "A"가 일치함 → 1
7.	"ABABCAB": 접두사 "AB"와 접미사 "AB"가 일치함 → 2
8.	"ABABCABA": 접두사 "ABA"와 접미사 "ABA"가 일치함 → 3
9.	"ABABCABAB": 접두사 "ABAB"와 접미사 "ABAB"가 일치함 → 4

// 실패함수 [0, 0, 1, 2, 0, 1, 2, 3, 4] 완성
```

### 실패함수 코드 구현

```swift
func failureFunc(_ s: String) -> [Int] {
    let arr = Array(s) // 문자열 배열
    var result = [Int](repeating: 0, count: s.count) // 실패함수 배열
    var j = 0 // 현재까지 일치한 접두사의 길이
    
    for i in 1..<s.count {
        while j > 0 && arr[i] != arr[j] { j = result[j-1] }
        if arr[i] == arr[j] { j += 1; result[i] = j }
    }
    
    return result
}
```

## 문제 풀이

### 16916번: 부분 문자열

```swift
func failureFunc(_ s: String) -> [Int] {
    let arr = Array(s) // 문자열 배열
    var f = [Int](repeating: 0, count: s.count) // 실패함수 배열
    var j = 0 // 현재까지 일치한 접두사의 길이
    
    for i in 1..<s.count {
        while j > 0 && arr[i] != arr[j] {
            j = f[j-1] // 실패함수를 참고
        }
        if arr[i] == arr[j] {
            j += 1; f[i] = j
        }
    }
    
    return f
}

let S = readLine()!, P = readLine()!
let (sArr, pArr) = (Array(S), Array(P))
let failure = failureFunc(P)
var j = 0 // 패턴 문자열의 위치
var ans = 0

for i in 0..<S.count { // S를 순회하며 패턴 P와 비교
    while j > 0 && sArr[i] != pArr[j] {  // 불일치 처리
        j = failure[j-1]
    }
    if sArr[i] == pArr[j] {
        j += 1
    }
    if j == pArr.count {
        ans = 1
        break
    }
}

print(ans)
```

**Comment by shippingpark** [comment]
# KMP 
정말 헷갈려요... 정말 드문 빈도로 나오는 알고리즘 (응용 가능성 거의 X) 
응용 없이 단순 패턴 매칭만 필요하다면, 굳이 KMP를 몰라도 가능할 수 있음 

코테만 고려한다면 굳이 알아야 할 필요 X 

## 정의 
문자열 A 안에 문자열 B가 들어있는 지 확인하는 알고리즘  
<img width="598" alt="image" src="https://github.com/user-attachments/assets/83316379-2b70-4149-aa66-f3e44c3fe59e">

알고리즘에 대한 이해 없이, for 문 두 개 돌려서 진행하는 경우 `시간 복잡도`가 O(A*B)
매번 B의 끝까지 가서 틀렸다는 사실을 인지한다면 최악의 경우 탄생 

KMP는 
패턴 매칭 문제를 O(A+B)에 해결할 수 있는 기적의 알고리즘 

### 실패함수 F(x)
> ...? 

아래는 챗구와 대화 후 납득가능한 선에서의 정리 

## KMP 알고리즘
KMP 알고리즘은 문자열 검색 알고리즘임. 
텍스트에서 특정 패턴을 효율적으로 찾는 방법임. 
핵심은 중복 연산을 줄이는 것이고, 이를 위해 실패 함수라는 걸 사용함. 
불필요한 비교를 피하는 방식

## 주요 개념
### Prefix와 Suffix:
패턴 내에서 접두사와 접미사가 일치하는 부분을 찾음.
불일치가 발생하면 이미 일치한 부분을 다시 검사하지 않고 다음 위치로 넘어감.
### 실패 함수 (LPS 배열):
LPS는 Longest Prefix Suffix의 줄임말로, 패턴의 각 위치에서 접두사와 접미사가 일치하는 최대 길이를 기록한 배열임.
이 배열을 실패 함수라고도 부름. 불일치 시, 패턴을 얼마나 건너뛸지 결정하는 데 도움을 줌.

## 과정
실패 함수(LPS 배열) 생성: 패턴에 대해 실패 함수를 먼저 생성함. 이 함수로 접두사와 접미사가 얼마나 일치하는지 기록함.

문자열 검색: 텍스트와 패턴을 비교하면서 불일치가 발생하면, 실패 함수를 참고해 패턴을 적절히 건너뛰고 계속 비교함.

### 예시
텍스트: ABABABABC
패턴: ABABC
실패 함수(LPS 배열) 생성:

패턴: A B A B C
실패 함수(LPS): 0 0 1 2 0
문자열 검색: 텍스트와 패턴을 차례로 비교하다가 불일치 발생하면, 실패 함수 보고 패턴을 건너뜀.

## 시간 복잡도
**O(N + M)**임. N은 텍스트 길이, M은 패턴 길이.
실패 함수 생성: O(M)
텍스트 검색: O(N)
실패 함수를 이용해 재검사 없이 효율적으로 패턴을 검색하는 알고리즘임.

**Comment by stealmh** [comment]
# KMP

문자열에 특정한 문자열이 포함하는지 찾는 알고리즘

시간을 좀더 가지고 공부해서 적겠읍니다. 하루만에 안되네ㅜㅜ
