### ISSUE TITLE
Trie

### ISSUE THREAD

**Issue by MUKER-WON** [TeddysRoom/Algo-rhythm#23]
10/17
[Link](https://www.youtube.com/watch?v=ZmLe4tc5XRI&list=PLtqbFd2VIQv4O6D6l9HcD732hdrnYb6CY&index=32)

**Comment by stealmh** [comment]
# 트라이

문자열을 효율적으로 처리하기 위한 트리 자료구조

단어 S가 있을 때 이를 삽입, 탐색, 삭제할 때는 단어의 길이만큼의 시간복잡도가 발생한다
단어를 배열에 저장하는 것과 비교했을 때 메모리를 4 * 글자의 종류배 만큼 사용
예를 들어 알파벳 대문자로만 구성이 되어있다 = 26 * 4

## Insert
APPLE이라는 영단어를 삽입한다고 할 때
A,P,P,L,E 순으로 탐색
현재 루트에는 A인 자식이 없기 때문에 A를 현재 정점의 자식에 추가하고 현재 정점을 루트에서 A로 옮긴다.
P 또한 정점에는 P라는 자식이 없기 때문에 현재 정점의 자식에 추가하고 현재 정점을 A에서 P로 옮긴다

이 과정을 거치면
루트 - A - P - P - L - E가 순서대로 삽입된다.
마지막 글자에는 별도의 표시를 해준다. 위 과정에서는 E가 마지막 글자

APPLY를 추가한다면 어떨까?

APPLE을 통해 추가된 정점을 사용해서 APPL 까지 올 수 있다.
하지만 L의 자식에는 Y가 없기 때문에 추가해준다.
따라서 마지막 글자는 Y과 E가 L의 자식으로 존재한다.


   A
    |
    P
    |
    P
    |
    L
    /\
(E) (Y)

()는 마지막 글자 
APPLE, APPLY

## Fetch
특정 문자열이 있는지 검색
   A
    |
    P
    |
    P
    |
    L
    /\
(E) (Y)
만약 APPLY라는 단어를 찾고자 할 때 삽입과 마찬가지로 타고 들어갈 수 있다
A -> P -> P -> L -> Y까지 갔을 때  Y가 마지막 글자라는 것을 알기때문에 해당 단어가 있다고 판단한다.
마지막 글자가 아닌데 단어의 구성이 된다고 하면 이는 성립할 수 없다
APP이라는 단어가 APPLY안에 있지만 P에 마지막 글자라는 표시가 없기 때문에 해당 단어가 없다고 판단한다

없는단어를 찾을 때도 마찬가지로 하위 자식이 없거나 끝나는 단어가 없다면 특정 단어는 없다고 판단할 수 있는 것

## Erase
   A
    |
    P
    |
    P
    |
    L
    /\
(E) (Y)
우리는 APPLE과 APPLY 두개의 단어를 들고 있다.
APPLY를 삭제하고 싶다면 어떻게 해야할까?
괄호를 지워주는 것으로 해결할 수 있다. 다만 상단의 노드를 삭제할 수는 없다.
이는 트라이 구조를 망치기 때문에 삭제를 하더라도 이전에 삽입했던 정점들은 계속 메모리에 남겨놔야 한다. 

-> 메모리 측면에서 비효율적이며 삭제가 빈번하게 발생하는 환경해서는 트라이는 적합하지 않음

**Comment by qwerty3345** [comment]
# 트라이 (Trie)

1. 개념
   - 문자열을 효율적으로 저장하고 검색하기 위한 트리 자료구조
   - 각 노드가 문자를 나타내며, 루트에서 특정 노드까지의 경로가 하나의 문자열을 표현

2. 특징
   - 삽입, 검색, 삭제 연산의 시간복잡도: O(|S|) (S: 문자열 길이)
   - 메모리 사용량이 큼 (일반적으로 배열로 저장하는 것보다 4 * 글자종류 배 더 사용)

3. 구현 방법
   - 각 노드에 자식 노드를 배열로 저장 (메모리 많이 사용, 빠른 접근)
   - 동적 배열, 연결 리스트, 이진 검색 트리, 해시 등으로 자식 노드 관리 (메모리 절약, 속도 저하)

4. 주요 연산
   - 삽입 (Insert): 문자열을 트리에 추가
   - 검색 (Find): 문자열이 트리에 존재하는지 확인
   - 삭제 (Erase): 문자열을 트리에서 제거

5. 활용
   - 자동 완성 기능
   - 접두사/접미사 관련 문제 해결

6. 장단점
   - 장점: 접두사 검색에 효율적
   - 단점: 메모리 사용량이 많음, 단순 문자열 검색에서는 해시나 이진 검색 트리보다 느림

7. 구현 시 주의사항
   - 메모리 제한을 고려하여 적절한 구현 방식 선택
   - 문자의 종류에 따라 자식 노드 저장 방식 결정

트라이는 특정 상황에서는 유용하지만, 메모리 사용량과 구현 복잡성 때문에 단순 문자열 검색에는 다른 자료구조가 더 적합함.
실제론 쓸 일이 거의 없다고 보면 됨.

## 문제 풀이
- 진행 중ㅇ....

**Comment by MUKER-WON** [comment]
# 트라이 (Trie)

- 문자열을 효율적으로 처리하기 위한 트리 자료구조
- 단어를 삽입/탐색/삭제할 때 O(단어의 길이) 만큼의 시간복잡도가 걸린다.
- 접두사나 접미사를 이용한 문자열 문제일 경우 트라이 알고리즘을 이용했을 때 유리할 수 있다.
- 메모리를 많이 차지한다는 단점이 있다.
- 루트노드는 공백 상태에서 시작한다.
- 리프노드는 문자열의 끝을 나타낸다.

## Insert

- 루트 노드에서 시작하여 문자열의 각 문자를 차례로 따라 내려간다.
- 경로에 없는 문자는 새롭게 노드를 만들어 연결한다.
- 마지막 문자는 리프노드로 설정하여 문자열의 끝을 나타낸다.

## Fetch

- Insert와 비슷한 진행흐름이다. 단어의 끝에 리프노드가 있다면 해당 단어를 포함하고 있음을 의미한다.

## Erase

- 마찬가지로 비슷한 진행흐름으로, 해당 단어가 존재한다면 리프노드를 지운다.
- 트라이 자료구조는 이전에 삽입한 정점들은 계속 메모리에 남아있게 되어 메모리의 측면에서 비효율적이고 삭제가 계속 발생하는 환경에서는 트라이가 적합하지 않다.

## 메모리 절약 방법
<img width="1523" alt="스크린샷 2024-10-17 오전 11 03 36" src="https://github.com/user-attachments/assets/9d76a277-8a2e-497e-b124-a3124fad31b5">


## 문제 풀이

### BOJ 14425번: 문자열 집합

- 문자열의 삽입/탐색/삭제만 있는 경우엔 고정된 크기의 배열 보다 이진 검색 트리나 해시가 더 빠르다.. 심지어 메모리도 많이 차지함
- 언제 사용하게 되나? 자동 완성 기능에 사용할 수 있다. 접두사를 하나하나 확인할 수 있다는 장점!
- 메모리 시간 차이
    - 고정된 크기의 배열
        - 메모리: 1355560KB
        - 시간: 1852ms
    - Set 자료구조
        - 메모리: 81108KB
        - 시간: 88ms

```swift
// 강의와 동일하게 고정된 배열 풀이

let (ROOT, MX) = (1, 10000 * 500 + 5)
var unused = 2
var chk = [Bool](repeating: false, count: MX) // 끝을 나타내는지 체크
var nxt = [[Int]](repeating: [Int](repeating: -1, count: 26), count: MX) // 다음 노드
var ans = 0

func c2i(_ c: Character) -> Int {
    return Int(c.asciiValue! - Character("a").asciiValue!)
}

func insert(_ s: String) {
    var node = ROOT
    for c in s {
        let cIdx = c2i(c)
        if nxt[node][cIdx] == -1 {
            nxt[node][cIdx] = unused
            unused += 1
        }
        node = nxt[node][cIdx]
    }
    chk[node] = true
}

func search(_ s: String) -> Bool {
    var node = ROOT
    for c in s {
        let cIdx = c2i(c)
        if nxt[node][cIdx] == -1 { return false }
        node = nxt[node][cIdx]
    }
    return chk[node]
}

let f = readLine()!.split(separator: " ").map { Int($0)! }
let N = f[0], M = f[1]

for _ in 0..<N { insert(readLine()!) }
for _ in 0..<M {
    let word = readLine()!
    if search(word) { ans += 1 }
}

print(ans)
```
