### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by qwerty3345** [TeddysRoom/Algo-rhythm#3]
9/11

**Comment by MUKER-WON** [comment]
## 재귀 (Reqursion)

- 함수가 자기 자신을 호출해 작업을 수행하는 기법이다.

## 재귀의 특징과 코멘트

- 절차적인 사고보단 귀납적인 사고를 통해 문제가 해결됨을 생각해보고 이해하는게 재귀를 사용하는데 도움이 된다.
- 올바른 재귀함수는 반드시 `Base Case(Base Condition)`로 수렴해야한다. Base Case란 재귀 호출을 멈추고 결과를 반환할 수 있는 조건을 의미한다. 만약 기본 조건이 설정되지 않으면 함수는 무한히 자기 자신을 호출하게 되어 에러가 발생하게 된다.
- 반복문에 비해 성능이 떨어질 수 있다. 동일한 연산을 여러 번 반복해야 하는 상황이 오면 재귀 함수는 불필요한 계산을 하게 된다. 예) 피보나치 수열
- 스택 메모리가 작게 잡혀있다면 재귀함수를 사용함에 있어 스택 오버플로우가 발생할 가능성이 더 높아진다.

## 문제풀이

### 백준 1629번: 곱셈

https://www.acmicpc.net/problem/1629

- 자연수가 무려 2,147,483,647가 되는 상황에서 O(n)의 시간복잡도로도 시간초과가 발생하는 상황이 된다.
- 해당 문제는 수학적 귀납법을 통한 재귀함수 사용을 통해 O(log N)의 시간복잡도를 가지게 하여 문제를 풀 수있다.

### 백준 11729번: 하노이 탑 이동 순서

https://www.acmicpc.net/problem/11729

- 자리1에 있는 기둥을 자리3까지 옮기는 과정을 짧게 풀어본다면
    - 기둥의 제일 밑에 있는 원판을 n개의 원판이 위에 있어 n이라 칭할 때, n원판 위에 있는 원판은 n을 뺀 나머지 n-1개의 원판이고 n-1개의 원판을 자리1에서 자리2로 옮길 수 있어야 합니다.
    - n번 원판을 자리1에서 자리3으로 옮깁니다.
    - n-1개의 원판을 자리2에서 자리3으로 옮깁니다.
- 해당 과정에서 n번 원판을 자리3에 놓으면 n-1번의 원판 부터는 같은 패턴으로 제일 밑에 있는 원판이 자리3에 갈 수 있게 반복됩니다.
- 즉 n개의 원판을 옮기는 것은 n-1개의 원판을 옮기는 문제로 축소되므로, 이를 재귀적으로 처리할 수 있다고 생각해야합니다.

### 백준 1074번: Z

https://www.acmicpc.net/problem/1074

- 큰배열에서 작은 배열로 4등분하면서 각 부분에 대해 순서를 재귀적으로 구할 수 있습니다.
- Z문제는 재귀의 핵심인 `큰 문제를 더 작은 문제들로 나눌 수 있는가?` 에 부합하고, `동일한 크기의 하위 문제들로 나눌 수 있기 때문에` 하위 문제들은 서로 독립적이라 볼 수 있어 `분할정복` 문제가 됩니다.
- 분할정복 특성상 결과를 결합하는 단계가 필요합니다. 따라서 Z문제도 하위 문제까지 모두 해결 했으면 다시 결합하여 전체 문제의 해답을 구할 수 있습니다.

<img src="https://github.com/user-attachments/assets/9177418e-aae9-499a-9fe3-2f12babb3e50" width="500">

## 공부하면서 본 참고 영상

- https://www.youtube.com/watch?v=NLcv5VGGQXU
    - 수학적 귀납법은 확장의 개념으로 접근하는게 아니라 축소의 개념으로 접근하는게 더욱 정확한 증명에 가깝다.

**Comment by stealmh** [comment]
# 재귀

하나의 함수에서 자기 자신을 다시 호출해 작업을 수행하는 알고리즘!

도미노를 예제로 들고 있음
제일 앞에 세워진 도미노를 쓰러트리게 되면 모든 도미노가 쓰러진다.
왜 쓰러지는지 설명하려면 2가지의 방법이 있다.
1. 1번이 쓰러지면 2번이 쓰러지고, 2번이 쓰러지면 3번이 쓰러지고 … 결국 모든 도미노가 쓰러질 것이기 때문이다.
2. 1번도미노가 쓰러지면 2번 도미노가 쓰러지는 것을 우리는 k번 도미노가 쓰러지면 k+1번째의 도미노가 쓰러진다는 것을 알 수 있다.
=> 곧바로 모든 도미노가 쓰러진다는 결론에 도달할 수 있어야 한다!
=> 절차지향적인 사고를 탈피해야 한다!

의역: 순차적 흐름을 강조하는 절차지향적 사고를 벗어나 귀납방식으로 흐름을 이해할 수 있도록 학습해보자.

## 재귀함수의 조건
1. Base Condition: 특정 입력에 대해서는 자기 자신을 호출하지 않고 종료되어야 함
2. 모든 입력은 1으로 수렴해야 함
끝없이 자기 자신을 탐색하기 때문에 빠져나올 수 있는 탈출구를 마련해야 하며, 이 탈출구는 한곳으로 집중되어야 함

ex) 100부터 1까지 값을 출력하는 재귀함수를 만든다고 할 때 1을 만나고 탈출할 수 있는 조건문이 없다면 지구끝까지 뚫고가서 런타임에러 발생 -> 앱터짐

## 재귀에 대한 정보1
재귀에 익숙하지 않다면 재귀로 짠 코드를 이해하는데 오랜 시간이 걸림 이를 위한 팁
1. 함수를 명확하게 정의하자
함수의 인자로 어떤 것을 받아야 하는지, 어디까지 계산하고 자기 자신에게 넘겨 줄 것인지

2. 모든 재귀함수는 반복문으로만 동일한 동작을 하는 함수를 만들 수 있음
재귀는 필요한 부분에 잘 적용한다면 코드가 간결해지지만 함수 호출 비용이 큰 연산
-> 메모리 및 시간 손해
-> 재귀를 쓰지 않아도 구현할 수 있다면 재귀 대신 반복문으로 코드를 작성하는 것이 좋음


## 재귀에 대한 정보2
자기 자신을 여러번 호출하게 되면 비효율적이다
ex. n번째 피보나치 수열을 반환하는 함수를 작성하면 n-1, n-2번째를 호출하고, 이 n-1 n-2로부터 다시 피보나치가 들어가면 중복해서 계산하는 값들이 반드시 생기게 됨 그 결과 시간복잡도를 초과해 문제가 풀리지 않을 수 있음

재귀함수가 자기 자신을 호출할 때 스택 영역에 계속 누적이 된다


## 연습문제
진짜 너무 이해가 안되서 도움주실분들 환영😂

**Comment by qwerty3345** [comment]
## 정리
- 영상 본거 요약 gpt 로 돌림! 얏호

1. 재귀는 함수가 자기 자신을 호출하여 문제를 해결하는 방식입니다. 이때, 특정 조건에서 함수 호출이 종료되는 base case가 필수적입니다.
2.	절차지향적 사고와 귀납적 사고: 절차지향적 사고는 코드의 흐름을 그대로 따라가는 방식이고, 귀납적 사고는 작은 문제에서 큰 문제로 확장하는 수학적 귀납법을 이용한 사고 방식입니다. 재귀는 귀납적 사고로 이해해야 효율적으로 사용할 수 있습니다.
3.	재귀 함수의 효율성: 재귀 함수는 반복적인 계산에서 비효율성을 초래할 수 있습니다. 특히, 중복 계산이 발생할 때 시간 복잡도가 급격히 증가하므로 메모이제이션이나 동적 프로그래밍을 사용해 개선할 수 있습니다.
4.	재귀의 한계와 스택 메모리: 재귀 호출이 깊어질 경우 스택 메모리 제한으로 인해 런타임 에러가 발생할 수 있으므로, 스택 메모리가 제한된 환경에서는 반복문으로 문제를 해결하는 것이 필요합니다.
5.	재귀의 시간 복잡도와 최적화: 재귀 함수의 호출이 많을 경우 예상보다 시간 복잡도가 커질 수 있으며, 이러한 문제를 해결하기 위해 메모이제이션이나 반복문을 사용하는 최적화가 필요합니다.



### BOJ 1629 곱셈
<details><summary>풀이</summary>
<p>

```swift
/**
10 % 7 = 3 // 결과 = 3
100 % 7 = 2
  - 3 * 10 % 7 = 2 // 결과 = 2
1000 % 7 = 6
  - 2 * 10 % 7 = 6
// 즉, 이전의 결과값에 대해서 10을 곱하고 나머지를 구해도 무방.

 100^100 = 100^50 * 100^50
 ...
 */
// 100 % 12
// 10 11 12
func powerMod(_ a: Int, _ b: Int, _ m: Int) -> Int {
    // base case: B가 0이면, A^0 = 1 (모든 수의 0제곱은 1이므로)
    if b == 0 {
        return 1
    }

    // 재귀적으로 절반의 거듭제곱 값을 구함
    var half = powerMod(a, b / 2, m)
    half = half * half % m

    // b가 홀수인 경우 추가적으로 a를 곱해줌
    if b % 2 == 1 {
        half = half * a % m
    }

    return half
}

let input = readLine()!.components(separatedBy: " ").compactMap(Int.init)
print(powerMod(input[0], input[1], input[2]))

```

</p>
</details>

**Comment by shippingpark** [comment]
# 재귀
