### ISSUE TITLE
Backtracking

### ISSUE THREAD

**Issue by qwerty3345** [TeddysRoom/Algo-rhythm#4]
9/12

**Comment by MUKER-WON** [comment]
## 백트래킹 (Back Tracking)

- 가능한 모든 후보 해를 탐색하면서 해당 경로가 해결책이 아닌 경우 되돌아가는 기법입니다.
- 주로 재귀에서 사용하며 탐색 과정에서 불필요한 경로를 배제하여 효율적으로 문제를 풀 수 있게 도와줍니다.

## 문제 풀이

### N과 M (1)

https://www.acmicpc.net/problem/15649

- 최대한 짧게 풀어본 코드

```swift
let I = readLine()!.split { $0 == " " }.map { Int($0)! }
let (N,M) = (I[0],I[1])

func task(_ arr: [Int]) {
    if arr.count == M { // 가지치기 부분
        print(arr.map { String($0) }.joined(separator: " "))
        return
    }
    for i in 1...N where !arr.contains(i) {
        task(arr+[i])
    }
}

task([])

// 약 100ms
```

- swift에서는 `print()` 함수가 호출 될 때마다 생각보다 비용이 많이 듭니다. 따라서 `print()` 문을 한번만 호출 할 수 있게 문자열 변수에 답을 저장해놨습니다.
- 위의 식에서는 `arr` 배열을 순회하며 같은 숫자가 있는지 검색하기 때문에 비용이 더 들었습니다. 유튜브 강의와 같게 방문처리 배열을 만들어서 풀면 같은 숫자가 있는지 확인하는 조건을 `O(1)` 만큼의 시간으로 줄일 수 있습니다.

```swift
let I = readLine()!.split { $0 == " " }.map { Int($0)! }
let (N,M) = (I[0],I[1])
var visited = Array(repeating: false, count: N+1)
var ans = ""

/// s: 한줄의 숫자 조합 문자열
/// c: s문자열에 들어있는 숫자 개수
func task(_ s: String, _ c: Int) {
    if c == M {
        ans += s+"\n"
        return
    }
    for i in 1...N {
        if !visited[i] {
            visited[i] = true
            task(s+"\(i) ", c+1)
            visited[i] = false
        }
    }
}

task("", 0)
print(ans)

// 약 40ms
```

**Comment by stealmh** [comment]
## 백트래킹

## 연습문제
#### N과 M
<details><summary>코드</summary>

```swift
import Foundation

/*
 4 2
 
 1 2
 1 3
 1 4
 2 1
 2 3
 2 4
 3 1
 3 2
 3 4
 4 1
 4 2
 4 3
 
 자연수 N과 M이 주어졌을 때, 아래 조건을 만족하는 길이가 M인 수열을 모두 구하는 프로그램을 작성하시오.

 1부터 N까지 자연수 중에서 중복 없이 M개를 고른 수열

 한 줄에 하나씩 문제의 조건을 만족하는 수열을 출력한다. 중복되는 수열을 여러 번 출력하면 안되며, 각 수열은 공백으로 구분해서 출력해야 한다.

 수열은 사전 순으로 증가하는 순서로 출력해야 한다.
 
 [입력]
 첫째 줄에 자연수 N과 M이 주어진다. (1 ≤ M ≤ N ≤ 8)

 */

let input = readLine()!.split(separator: " ").map { Int($0)! }
let n = input[0],
    m = input[1]

var array = [Int]()

func backTracking(_ input: [Int]) {
    if array.count == m {
        print(array.map { String($0) }.joined(separator: " "))
        return
    }
    
    for i in 1...n {
        if !input.contains(i) {
            array.append(i)
            backTracking(array)
            array.removeLast()
        }
    }
}

backTracking(array)
```
</details>

작성중😃

**Comment by qwerty3345** [comment]
## 백트래킹

### 개념
- 해를 찾는 도중 해가 아니어서 막히면, 되돌아가서 다시 해를 찾아가는 기법. 
- 최적화 문제와 결정 문제를 푸는 방법.
- **⭐ 보통 모든 수를 확인해야 하는 경우, for 문의 깊이가 경우에 따라 동적으로 달라질 때 많이 사용!!!**
- 재귀적 구조: 주로 재귀함수를 사용하여 해결. 각 상태에서 새로운 후보를 선택하거나 선택하지 않는 방식으로 진행.
- 구현 패턴: 보통 재귀함수 내에서 조건을 만족하는지를 확인하고, 만족하면 다음 단계로 진행하며, 만족하지 않으면 이전 상태로 돌아가 다른 경로를 탐색.
- 가지치기: 불필요한 경로를 조기에 탐색에서 제외하여 효율성을 높이는 기법.

### 주의사항
- 구현 복잡도: 백트래킹은 구현 난이도가 높고, 특히 실수를 발견하기 어렵기 때문에 꼼꼼한 디버깅과 테스트가 필요.
- 시간 복잡도: 상태 공간이 커질 경우 탐색 시간이 급격히 증가할 수 있음. 가지치기를 적절히 사용해 시간 복잡도를 줄이는 것이 중요.
- 재귀 구조 익숙해지기: 백트래킹은 재귀적 사고가 중요하며, 코드를 작성할 때 함수의 흐름과 상태 변화를 철저히 이해해야 함.

### 사용 예

- 백트래킹은 **모든 가능한 경우의 수를 탐색**해야 하거나, **결정 문제**에서 특정 조건을 만족하는 해를 찾아야 하는 경우에 많이 사용됩니다. 특히, 탐색 공간이 큰 문제에서 불필요한 탐색을 줄이고 효율적으로 해를 구할 때 유용함

1. **조합 탐색 문제**  
   - 모든 경우의 수를 찾거나 특정 조건을 만족하는 부분집합을 찾아야 할 때 사용됩니다.
   - 예시: 부분집합의 합 문제, 수열에서 특정 조건을 만족하는 부분집합 구하기.
   
2. **순열 및 조합 생성 문제**  
   - 주어진 숫자나 문자에서 가능한 모든 순열이나 조합을 구하는 문제에서 사용됩니다.
   - 예시: N과 M 시리즈 문제 (BOJ 15649), 숫자 배열에서 가능한 모든 순열 생성.

3. **N-Queens 문제**  
   - N×N 체스판 위에 N개의 퀸을 서로 공격하지 않도록 배치하는 문제. 체스판의 모든 가능한 배치를 탐색하면서 조건을 만족하는 해를 찾습니다.
   - 예시: N-Queens 문제 (BOJ 9663).

4. **미로 탐색 문제**  
   - 미로에서 시작점에서 출발해 목적지까지 도달하는 모든 경로를 탐색하는 문제.
   - 예시: 미로의 각 경로를 재귀적으로 탐색하여 최적의 경로 찾기.

5. **그래프 탐색 문제**  
   - 그래프 상에서 모든 가능한 경로를 탐색해야 할 때, 백트래킹을 사용하여 최적의 경로나 특정 조건을 만족하는 경로를 찾아냅니다.
   - 예시: Hamiltonian Path, 모든 정점을 한 번씩 방문하는 경로 탐색.

6. **Sudoku 문제**  
   - 주어진 수학적 조건을 만족하면서 빈 칸에 숫자를 채워 넣는 문제.
   - 예시: Sudoku 퍼즐에서 모든 가능성을 시도하며 해를 찾는 방식.

### 요약
백트래킹은 **모든 경우의 수를 탐색**해야 하거나 **결정 문제**에서 특정 조건을 만족하는 해를 찾기 위한 상황에서 유용합니다. 순열, 조합, 미로 탐색, N-Queens와 같은 전형적인 문제에서 자주 활용됩니다.

### 참고한 영상
- [바킹독](https://www.youtube.com/watch?v=jZwf4OPlhtk&list=PLtqbFd2VIQv4O6D6l9HcD732hdrnYb6CY&index=14)
- [개발자 장고 - 알기 쉬움!](https://youtu.be/atTzqxbt4DM?si=srFmdkStF0Ho86c4) 


### [BOJ 15649 - N과 M (1) ](https://www.acmicpc.net/problem/15649)
<details><summary>코드</summary>
<p>

```swift
let input = readLine()!.components(separatedBy: " ").compactMap { Int($0) }
let m = input[0]
let n = input[1]

// print("m: \(m), n: \(n)")

var result: [[Int]] = []

func recr(_ nums: [Int], _ res: [Int]) {
    // print("res.count == n: \(res.count == n)")
    // print("res.count: \(res.count) n: \(n)")

    if res.count == n {
        // print(res)
        result.append(res)
        return
    }

    // print("nums: \(nums), res: \(res)")
    for i in 0..<nums.count {
        var res = res
        var nums = nums
        let num = nums.remove(at: i)
        res.append(num)
        recr(nums, res)
    }
}

// print("result: \(result)")
recr((1...m).map { $0 }, [])

result.forEach { r in
    print(r.map { String($0) }.joined(separator: " "))
}
```
</p>
</details>

**Comment by shippingpark** [comment]
# 개념 
> 미연시. 내가 선택한 경로에 대해 끝까지 진입하고, 게임이 종료된다면 (조건에 부합하다면) 선택 이전으로 돌아가 다른 선택. 

## N과 M문제 

```swift 
// https://www.acmicpc.net/submit/15649

import Foundation

let input: [Int] = readLine()!.components(separatedBy: " ").map{ Int(String($0))! }
let N = input[0], M = input[1]

var arr = Array(repeating: 0, count: 10) // 결과 값이 담길 배열 [1, 2, 3] <- 첫 번째 조합 예시
var isUsed = Array(repeating: false, count: 10) // index가 곧 키값 (선택된 i에 대한 사용 여부)

func nAndM(k: Int) { // 0<=k<=M // 현재 arr이 뽑힌 상태에 대한 정보
    if k == M { // 만약 모든 숫자가 뽑힌 상황이라면
      for i in 0..<M {
        print(arr[i], separator: " ")
      }
      return
    }
  
  for i in 1...N {
    if !isUsed[i] {
      arr[k] = i
      isUsed[i] = true // 방문처리
      nAndM(k: k+1) // 1개 뽑힌 상황 대한 실행
      isUsed[i] = false
    }
  }
}

nAndM(k: 0)
```
