### ISSUE TITLE
Greedy

### ISSUE THREAD

**Issue by MUKER-WON** [TeddysRoom/Algo-rhythm#9]
9/24
[링크](https://www.youtube.com/watch?v=De0Qg-2O80c&list=PLtqbFd2VIQv4O6D6l9HcD732hdrnYb6CY&index=18)

**Comment by stealmh** [comment]
# 그리디

매 선택에서 가장 최적인 답을 근시안적으로 택하는 알고리즘!

근시안적: 짧은 시야로만 바라보는 것
당장 눈앞의 이익이나 상황만을 고려하고 장기적인 결과나 전체적인 맥락을 보지 못하는 태도

## 풀이의 흐름
1. 관찰을 통해 탐색 범위를 줄이는 방법을 고안
2. 탐색 범위를 줄여도 올바른 결과를 낸다는 사실을 수학적으로 증명

일단 제출하고 틀리면 빠르게 손절하자.
=> 보통 풀이가 잘못된 경우가 많다..

## 연습문제
11047 동전
<details>
<summary>코드</summary>

```swift
let input = readLine()!.split(separator: " ").map { Int($0)! }
let n = input[0]
var m = input[1]

var coins: [Int] = []
var temp = 0

for _ in 0..<n { coins.append(Int(readLine()!)!) }
coins.reverse()

for i in 0..<n where coins[i] <= m {
    temp += m / coins[i]
    m %= coins[i]
}

print(temp)
```
</details>

1931 회의실 배정
<details>
<summary>코드</summary>

```swift
 struct Schedule {
     let start: Int
     let end: Int
 }

 let n = Int(readLine()!)!

 var listup: [Schedule] = []
 var endTime: Int = 0
 var count: Int = 0

 for i in 0..<n {
     let input = readLine()!.split(separator: " ").map { Int($0)! }
     let start = input[0], end = input[1]
     listup.append(
         Schedule(start: start, end: end)
     )
 }

 listup.sort { sch1, sch2 in
     if sch1.end == sch2.end {
         return sch1.start <= sch2.start
     }
     return sch1.end <= sch2.end
 }
 print(listup)

 for list in listup {
     if list.start >= endTime {
         endTime = list.end
         count += 1
     }
 }

 print(count)
```
</details>
2217 로프
<details>
<summary>코드</summary>

```swift
var n = Int(readLine()!)!
var array = [Int]()
var answer: Int = -1

for i in 0..<n {
    let input = Int(readLine()!)!
    array.append(input)
}

array.sort(by: >)

for i in array {
    let weight = i * n
    answer = max(answer, weight)
    n -= 1
}
print(answer)
```
</details>

**Comment by MUKER-WON** [comment]
## 그리디 (Greedy)

- 문제를 해결할 때 각 단계에서 현재 가장 최선의 선택을 하는 알고리즘
- 여기서 최선이란, 매 순간 최적이라고 판단되는 선택을 함으로써 적체적인 해답을 구하는 것을 말함
- 결국 올바른 풀이를 생각해서 풀라는건데, 내가 생각한 풀이가 최대한 명제와 증명이 정확한지 검증을 해보고 코드를 써내려가는 방법도 좋다. 빈약한 증명으로 시간은 시간대로 잡아먹고 다시 원점으로 돌아올 수 있어 주의 해야한다.
- 마찬가지로 그리디로 풀지 못하는 문제인데 그리디로 풀릴거 같다고 판단하면 시간만 잡아먹고 원점으로 돌아올 수 있어서 해당 문제가 그리디 문제인지 잘 판단해야한다.

## 그리디 알고리즘 풀이 흐름

1. 관찰을 통해 탐색 범위를 줄이는 방법을 고안
2. 탐색 범위를 줄여 올바른 결과를 낸다는 사실을 수학적으로 증명
3. 방법을 통해 구현

## 문제 풀이

### 백준 1026번: 보물

```swift
import Foundation

let N = Int(readLine()!)!
let A = readLine()!.split { $0 == " " }.map { Int($0)! }.sorted(by: >)
let B = readLine()!.split { $0 == " " }.map { Int($0)! }.sorted(by: <)
print((0..<N).map { A[$0]*B[$0] }.reduce(0,+))
```

**Comment by shippingpark** [comment]
> 관찰을 통해 탐색 범위를 줄이는 알고리즘  

### 이상적인 풀이 흐름 
1. 관찰을 통해 탐색 범위를 줄이는 방법을 고안한다 
2. 탐색 범위를 줄여도 올바른 결과를 낸다는 사실을 수학적으로 증명한다 
3. 구현해서 문제를 통과한다 

### tip
그리디로 푸는 걸 확신할 수 있다면 푼다 
확신할 수 없다면, 종료가 2-40분 남았을 때 건드려 본다 (풀이가 잘못될 확률이 높기 때문)

괜히 그리디로 착각해서 괴로워하지 말기 

직관적으로 맞는 것 같다, 와 
수학적으로 옳다엔 큰 차이가 있음 

### 귀류법에 의한 증명 
명제가 거짓임을 가정할 때, 모순이 발생함을 보여 증명하는 방식 
루트 2가 무리수임을 증명할 때 처음 등장 

### 11047번 동전 0 문제 
```swift 
import Foundation

let input = readLine()!.split(separator: " ").compactMap { Int($0) }, 
N = input[0]
var K = input[1]
var arr = Array(repeating: 0, count: N)
var result = 0

for i in 0..<N { arr[i] = Int(readLine()!)! }
for i in (0..<N).reversed() {
  result += K/arr[i]
  K %= arr[i]
}

print(result)
```

> 이 문제는 솔직히 뭐가 그리디 풀이인지 잘 와닿지 않는다. (어떤 영역에 대한 탐색을 줄인건지...)
